# Generated by Django 3.2 on 2021-04-26 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='added_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
